auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: shipengfei92.cn
url: http://shipengfei92.cn
feed: /atom.xml
author_info: <a href="http://shipengfei92.cn/">PengfeiShi</a>
